package:
    type:           yii2-extension
    name:           hidev-vendor
    title:          AdvancedHosters vendor configuration for HiDev
    headline:       AdvancedHosters HiDev config
    keywords:       advanced hosters, hidev, vendor config
    namespace:      advancedhosters\hidev\vendor
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin provides [AdvancedHosters](https://github.com/advancedhosters) vendor configuration for HiDev.

        Provides AdvancedHosters information and settings:

        * general data: vendor name and company title
        * contact data: email, forum, github page
        * authors data: names, emails, github and home pages
        * default license: proprietary

        See [src/config/goals.yml](src/config/goals.yml).

include:
    - src/config/goals.yml
