vendor:
    name:       advancedhosters
    title:      AdvancedHosters
    homepage:   https://advancedhosters.com/
    email:      support@advancedhosters.com
    authors:
        'Andrii Vasyliev':
            email:      sol@hiqdev.com
            homepage:   https://hipanel.com/
